/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Quote = {
  text?: string;
  attribution?: string;
};

export type Hymnal = {
  _type: "hymnal";
  kicker?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  deck?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  columns?: Array<{
    header?: string;
    subhead?: string;
    rows?: Array<{
      number?: string;
      title?: string;
      sub?: string;
      duration?: string;
      href?: string;
      _type: "hymnRow";
      _key: string;
    }>;
    _type: "hymnalColumn";
    _key: string;
  }>;
};

export type Stations = {
  _type: "stations";
  kicker?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  deck?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  items?: Array<{
    roman?: string;
    years?: string;
    location?: string;
    heading?: string;
    where?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    quote?: Quote;
    _type: "stationItem";
    _key: string;
  }>;
};

export type ScriptureStrip = {
  _type: "scriptureStrip";
  quote?: string;
  reference?: string;
};

export type HymnHero = {
  _type: "hymnHero";
  eyebrow?: string;
  romanNumeral?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lede?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  metaItems?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  glassCaptionTop?: string;
  glassQuote?: string;
};

export type NextEssay = {
  _type: "nextEssay";
  kicker?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cards?: Array<{
    roman?: string;
    tag?: string;
    cardHeading?: string;
    cta?: string;
    href?: string;
    colorScheme?: "barn" | "denim" | "brass";
    _type: "nextCard";
    _key: string;
  }>;
};

export type PullQuote = {
  _type: "pullQuote";
  kicker?: string;
  quote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  attribution?: Array<string>;
  background?: "ink" | "accentDeep";
  borderTone?: "accent" | "brass";
};

export type CardGrid = {
  _type: "cardGrid";
  kicker?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  deck?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cards?: Array<{
    roman?: string;
    tag?: string;
    cardHeading?: string;
    cardBody?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "gridCard";
    _key: string;
  }>;
};

export type SteppedList = {
  _type: "steppedList";
  kicker?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  deck?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  items?: Array<{
    years?: string;
    label?: string;
    tag?: Array<{
      label?: string;
      value?: string;
      _key: string;
    }>;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    cuts?: Array<{
      cutLabel?: string;
      cutTitle?: string;
      cutDuration?: string;
      cutHref?: string;
      _type: "cutItem";
      _key: string;
    }>;
    _type: "eraItem";
    _key: string;
  }>;
};

export type VinylHero = {
  _type: "vinylHero";
  eyebrow?: string;
  romanNumeral?: string;
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lede?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  metaItems?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  vinylTop?: string;
  vinylTitle?: string;
  vinylBottom?: string;
  tickerItems?: Array<string>;
};

export type KulturenTimelineEntry = {
  _type: "kulturenTimelineEntry";
  year?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type KulturenTimeline = {
  _type: "kulturenTimeline";
  label?: string;
  entries?: Array<
    {
      _key: string;
    } & KulturenTimelineEntry
  >;
};

export type KulturenSideNote = {
  _type: "kulturenSideNote";
  label?: string;
  value?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  emphasis?: "default" | "cash";
};

export type TimelineEvent = {
  _type: "timelineEvent";
  year?: string;
  place?: string;
  heading?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type VinylTile = {
  _type: "vinylTile";
  cornerNumber?: string;
  cornerTag?: string;
  vinylAccent?: "barn" | "denim" | "brass";
  sleeveText?: string;
  vinylTopLabel?: string;
  vinylTitle?: string;
  vinylBottomLabel?: string;
  heading?: string;
  subhead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tracklist?: Array<
    {
      _key: string;
    } & VinylTrack
  >;
  linkText?: string;
  linkHref?: string;
};

export type VinylTrack = {
  _type: "vinylTrack";
  track?: string;
  title?: string;
  duration?: string;
};

export type TickerItem = {
  _type: "tickerItem";
  year?: string;
  milestone?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type FooterQuote = {
  _type: "footerQuote";
  text?: string;
  attribution?: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  title?: string;
  links?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type NavGroup = {
  _type: "navGroup";
  label?: string;
  href?: string;
  children?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: "navLink";
  mark?: string;
  label?: string;
  href?: string;
};

export type Masthead = {
  _type: "masthead";
  kicker?: string;
  name?: string;
  sub?: string;
  leftLine1?: string;
  leftLine2?: string;
  rightLine1?: string;
  rightLine2?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  accentColor?: "barn" | "denim" | "brass";
  blocks?: Array<
    | ({
        _key: string;
      } & VinylHero)
    | ({
        _key: string;
      } & SteppedList)
    | ({
        _key: string;
      } & CardGrid)
    | ({
        _key: string;
      } & PullQuote)
    | ({
        _key: string;
      } & NextEssay)
    | ({
        _key: string;
      } & HymnHero)
    | ({
        _key: string;
      } & ScriptureStrip)
    | ({
        _key: string;
      } & Stations)
    | ({
        _key: string;
      } & Hymnal)
  >;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LandscapeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "landscape";
};

export type ArchiveEntry = {
  _id: string;
  _type: "archiveEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  landscape?: LandscapeReference;
  publishedAt?: string;
  kind?: "anmeldelse" | "fund" | "fodnote" | "note";
  summary?: string;
};

export type Landscape = {
  _id: string;
  _type: "landscape";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  shortName?: string;
  slug?: Slug;
  order?: number;
  romanNumeral?: string;
  toponym?: string;
  period?: string;
  accentColor?: "barn" | "denim" | "brass";
  eyebrow?: string;
  motto?: string;
  deck?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  topicsLabel?: string;
  topics?: Array<string>;
  crumbBackText?: string;
  crumbBackHref?: string;
  emptyMeta?: string;
  emptyLabel?: string;
  emptyHeading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  emptyBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  emptyActions?: Array<{
    text?: string;
    href?: string;
    style?: "primary" | "secondary";
    _key: string;
  }>;
  kulturenBgVariant?: "paper" | "paper-2" | "dark";
  kulturenEssay?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h4" | "pull";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  kulturenSidebar?: Array<
    | ({
        _key: string;
      } & KulturenSideNote)
    | ({
        _key: string;
      } & KulturenTimeline)
  >;
  kulturenArchiveCta?: string;
  kulturenCardTag?: string;
  seo?: Seo;
};

export type KulturenPage = {
  _id: string;
  _type: "kulturenPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    subhead?: string;
    deck?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  chips?: {
    label?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    count?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  intro?: {
    kicker?: string;
    heading?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    signature?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  outro?: {
    kicker?: string;
    heading?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    actions?: Array<{
      text?: string;
      href?: string;
      style?: "primary" | "secondary";
      _key: string;
    }>;
    cardLead?: string;
    cardHeading?: string;
  };
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    kicker?: string;
    title?: string;
    deck?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    meta?: Array<string>;
  };
  signatureCard?: {
    stamp?: string;
    foreLabel?: string;
    quote?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    scripture?: {
      text?: string;
      reference?: string;
    };
  };
  ticker?: {
    items?: Array<
      {
        _key: string;
      } & TickerItem
    >;
  };
  vinyls?: {
    kicker?: string;
    heading?: string;
    deck?: string;
    items?: Array<
      {
        _key: string;
      } & VinylTile
    >;
  };
  historicalThread?: {
    kicker?: string;
    heading?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    intro?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    timeline?: Array<
      {
        _key: string;
      } & TimelineEvent
    >;
  };
  hymn?: {
    kicker?: string;
    quote?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    attribution?: string;
  };
  contact?: {
    kicker?: string;
    heading?: string;
    deck?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    bookingLabel?: string;
    bookingHeading?: string;
    bookingBody?: string;
    bookingLinkText?: string;
    bookingLinkHref?: string;
  };
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  masthead?: Masthead;
  nav?: Array<
    {
      _key: string;
    } & NavGroup
  >;
  cta?: Cta;
  footerMark?: string;
  footerBlurb?: string;
  footerQuote?: FooterQuote;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  footerBottomCopyright?: string;
  footerBottomTagline?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Quote
  | Hymnal
  | Stations
  | ScriptureStrip
  | HymnHero
  | NextEssay
  | PullQuote
  | CardGrid
  | SteppedList
  | VinylHero
  | KulturenTimelineEntry
  | KulturenTimeline
  | KulturenSideNote
  | TimelineEvent
  | VinylTile
  | VinylTrack
  | TickerItem
  | SanityImageAssetReference
  | Seo
  | FooterQuote
  | FooterColumn
  | Cta
  | NavGroup
  | NavLink
  | Masthead
  | Page
  | Slug
  | LandscapeReference
  | ArchiveEntry
  | Landscape
  | KulturenPage
  | HomePage
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/global.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    masthead,    nav,    cta,    footerMark,    footerBlurb,    footerQuote,    footerColumns,    footerBottomCopyright,    footerBottomTagline,    seo{      title,      description,      ogImage{ asset->{url, metadata{dimensions}}, alt }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  masthead: Masthead | null;
  nav: Array<
    {
      _key: string;
    } & NavGroup
  > | null;
  cta: Cta | null;
  footerMark: string | null;
  footerBlurb: string | null;
  footerQuote: FooterQuote | null;
  footerColumns: Array<
    {
      _key: string;
    } & FooterColumn
  > | null;
  footerBottomCopyright: string | null;
  footerBottomTagline: string | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/home.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    hero{      kicker,      title,      deck,      meta    },    signatureCard{      stamp,      foreLabel,      quote,      body,      scripture{ text, reference }    },    ticker{      items[]{ year, milestone }    },    vinyls{      kicker,      heading,      deck,      items[]{        cornerNumber,        cornerTag,        vinylAccent,        sleeveText,        vinylTopLabel,        vinylTitle,        vinylBottomLabel,        heading,        subhead,        body,        tracklist[]{ track, title, duration },        linkText,        linkHref      }    },    historicalThread{      kicker,      heading,      intro,      timeline[]{ year, place, heading, description }    },    hymn{      kicker,      quote,      attribution    },    contact{      kicker,      heading,      deck,      bookingLabel,      bookingHeading,      bookingBody,      bookingLinkText,      bookingLinkHref    },    seo{      title,      description,      ogImage{ asset->{url, metadata{dimensions}}, alt }    }  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    kicker: string | null;
    title: string | null;
    deck: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    meta: Array<string> | null;
  } | null;
  signatureCard: {
    stamp: string | null;
    foreLabel: string | null;
    quote: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    scripture: {
      text: string | null;
      reference: string | null;
    } | null;
  } | null;
  ticker: {
    items: Array<{
      year: string | null;
      milestone: string | null;
    }> | null;
  } | null;
  vinyls: {
    kicker: string | null;
    heading: string | null;
    deck: string | null;
    items: Array<{
      cornerNumber: string | null;
      cornerTag: string | null;
      vinylAccent: "barn" | "brass" | "denim" | null;
      sleeveText: string | null;
      vinylTopLabel: string | null;
      vinylTitle: string | null;
      vinylBottomLabel: string | null;
      heading: string | null;
      subhead: string | null;
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      tracklist: Array<{
        track: string | null;
        title: string | null;
        duration: string | null;
      }> | null;
      linkText: string | null;
      linkHref: string | null;
    }> | null;
  } | null;
  historicalThread: {
    kicker: string | null;
    heading: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    intro: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    timeline: Array<{
      year: string | null;
      place: string | null;
      heading: string | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }> | null;
  } | null;
  hymn: {
    kicker: string | null;
    quote: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    attribution: string | null;
  } | null;
  contact: {
    kicker: string | null;
    heading: string | null;
    deck: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    bookingLabel: string | null;
    bookingHeading: string | null;
    bookingBody: string | null;
    bookingLinkText: string | null;
    bookingLinkHref: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/kulturen.ts
// Variable: KULTUREN_QUERY
// Query: *[_type == "kulturenPage"][0]{    hero{ eyebrow, title, subhead, deck },    chips{ label, count },    intro{ kicker, heading, signature, body },    outro{      kicker,      heading,      body,      actions[]{ text, href, style },      cardLead,      cardHeading    },    seo{      title,      description,      ogImage{ asset->{ url, metadata{ dimensions } }, alt }    },    "landscapes": *[_type == "landscape"] | order(order asc){      "slug": slug.current,      romanNumeral,      toponym,      period,      name,      motto,      shortName,      kulturenBgVariant,      kulturenArchiveCta,      kulturenCardTag,      kulturenEssay,      kulturenSidebar[]{        _type,        _key,        label,        emphasis,        value,        entries[]{ _key, year, text }      }    }  }
export type KULTUREN_QUERY_RESULT = {
  hero: {
    eyebrow: string | null;
    title: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    subhead: string | null;
    deck: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  chips: {
    label: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    count: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  intro: {
    kicker: string | null;
    heading: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    signature: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  outro: {
    kicker: string | null;
    heading: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    actions: Array<{
      text: string | null;
      href: string | null;
      style: "primary" | "secondary" | null;
    }> | null;
    cardLead: string | null;
    cardHeading: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
  landscapes: Array<{
    slug: string | null;
    romanNumeral: string | null;
    toponym: string | null;
    period: string | null;
    name: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    motto: string | null;
    shortName: string | null;
    kulturenBgVariant: "dark" | "paper-2" | "paper" | null;
    kulturenArchiveCta: string | null;
    kulturenCardTag: string | null;
    kulturenEssay: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h4" | "normal" | "pull";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    kulturenSidebar: Array<
      | {
          _type: "kulturenSideNote";
          _key: string;
          label: string | null;
          emphasis: "cash" | "default" | null;
          value: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          entries: null;
        }
      | {
          _type: "kulturenTimeline";
          _key: string;
          label: string | null;
          emphasis: null;
          value: null;
          entries: Array<{
            _key: string;
            year: string | null;
            text: Array<{
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal";
              listItem?: never;
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }> | null;
          }> | null;
        }
    > | null;
  }>;
} | null;

// Source: sanity/queries/landscape.ts
// Variable: LANDSCAPE_QUERY
// Query: *[_type == "landscape" && slug.current == $slug][0]{    name,    "slug": slug.current,    order,    romanNumeral,    toponym,    period,    accentColor,    eyebrow,    motto,    deck,    topicsLabel,    topics,    crumbBackText,    crumbBackHref,    emptyMeta,    emptyLabel,    emptyHeading,    emptyBody,    emptyActions[]{ text, href, style },    "entries": *[_type == "archiveEntry" && landscape._ref == ^._id] | order(publishedAt desc){      title,      "slug": slug.current,      publishedAt,      kind,      summary    },    seo{      title,      description,      ogImage{ asset->{url, metadata{dimensions}}, alt }    }  }
export type LANDSCAPE_QUERY_RESULT = {
  name: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  order: number | null;
  romanNumeral: string | null;
  toponym: string | null;
  period: string | null;
  accentColor: "barn" | "brass" | "denim" | null;
  eyebrow: string | null;
  motto: string | null;
  deck: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  topicsLabel: string | null;
  topics: Array<string> | null;
  crumbBackText: string | null;
  crumbBackHref: string | null;
  emptyMeta: string | null;
  emptyLabel: string | null;
  emptyHeading: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  emptyBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  emptyActions: Array<{
    text: string | null;
    href: string | null;
    style: "primary" | "secondary" | null;
  }> | null;
  entries: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    kind: "anmeldelse" | "fodnote" | "fund" | "note" | null;
    summary: string | null;
  }>;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/landscape.ts
// Variable: LANDSCAPE_SIBLINGS_QUERY
// Query: *[_type == "landscape"] | order(order asc){    "slug": slug.current,    romanNumeral,    shortName,    order  }
export type LANDSCAPE_SIBLINGS_QUERY_RESULT = Array<{
  slug: string | null;
  romanNumeral: string | null;
  shortName: string | null;
  order: number | null;
}>;

// Source: sanity/queries/page.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title,    accentColor,    blocks[]{      _type,      _key,      _type == "vinylHero" => {        eyebrow,        romanNumeral,        heading,        lede,        metaItems[]{ label, value },        vinylTop,        vinylTitle,        vinylBottom,        tickerItems      },      _type == "steppedList" => {        kicker,        heading,        deck,        items[]{          years,          label,          tag[]{ label, value },          body,          cuts[]{ cutLabel, cutTitle, cutDuration, cutHref }        }      },      _type == "cardGrid" => {        kicker,        heading,        deck,        cards[]{ roman, tag, cardHeading, cardBody }      },      _type == "pullQuote" => {        kicker,        quote,        attribution,        background,        borderTone      },      _type == "nextEssay" => {        kicker,        heading,        cards[]{ roman, tag, cardHeading, cta, href, colorScheme }      },      _type == "hymnHero" => {        eyebrow,        romanNumeral,        heading,        lede,        metaItems[]{ label, value },        glassCaptionTop,        glassQuote      },      _type == "scriptureStrip" => {        quote,        reference      },      _type == "stations" => {        kicker,        heading,        deck,        items[]{          roman,          years,          location,          heading,          where,          body,          quote{ text, attribution }        }      },      _type == "hymnal" => {        kicker,        heading,        deck,        columns[]{          header,          subhead,          rows[]{ number, title, sub, duration, href }        }      }    },    seo{      title,      description,      ogImage{ asset->{ url, metadata{ dimensions } }, alt }    }  }
export type PAGE_QUERY_RESULT = {
  title: string | null;
  accentColor: "barn" | "brass" | "denim" | null;
  blocks: Array<
    | {
        _type: "cardGrid";
        _key: string;
        kicker: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        deck: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        cards: Array<{
          roman: string | null;
          tag: string | null;
          cardHeading: string | null;
          cardBody: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
        }> | null;
      }
    | {
        _type: "hymnal";
        _key: string;
        kicker: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        deck: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        columns: Array<{
          header: string | null;
          subhead: string | null;
          rows: Array<{
            number: string | null;
            title: string | null;
            sub: string | null;
            duration: string | null;
            href: string | null;
          }> | null;
        }> | null;
      }
    | {
        _type: "hymnHero";
        _key: string;
        eyebrow: string | null;
        romanNumeral: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        lede: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        metaItems: Array<{
          label: string | null;
          value: string | null;
        }> | null;
        glassCaptionTop: string | null;
        glassQuote: string | null;
      }
    | {
        _type: "nextEssay";
        _key: string;
        kicker: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        cards: Array<{
          roman: string | null;
          tag: string | null;
          cardHeading: string | null;
          cta: string | null;
          href: string | null;
          colorScheme: "barn" | "brass" | "denim" | null;
        }> | null;
      }
    | {
        _type: "pullQuote";
        _key: string;
        kicker: string | null;
        quote: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        attribution: Array<string> | null;
        background: "accentDeep" | "ink" | null;
        borderTone: "accent" | "brass" | null;
      }
    | {
        _type: "scriptureStrip";
        _key: string;
        quote: string | null;
        reference: string | null;
      }
    | {
        _type: "stations";
        _key: string;
        kicker: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        deck: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        items: Array<{
          roman: string | null;
          years: string | null;
          location: string | null;
          heading: string | null;
          where: string | null;
          body: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          quote: {
            text: string | null;
            attribution: string | null;
          } | null;
        }> | null;
      }
    | {
        _type: "steppedList";
        _key: string;
        kicker: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        deck: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        items: Array<{
          years: string | null;
          label: string | null;
          tag: Array<{
            label: string | null;
            value: string | null;
          }> | null;
          body: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "normal";
            listItem?: never;
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          cuts: Array<{
            cutLabel: string | null;
            cutTitle: string | null;
            cutDuration: string | null;
            cutHref: string | null;
          }> | null;
        }> | null;
      }
    | {
        _type: "vinylHero";
        _key: string;
        eyebrow: string | null;
        romanNumeral: string | null;
        heading: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        lede: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        metaItems: Array<{
          label: string | null;
          value: string | null;
        }> | null;
        vinylTop: string | null;
        vinylTitle: string | null;
        vinylBottom: string | null;
        tickerItems: Array<string> | null;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/router.ts
// Variable: SLUG_TYPE_QUERY
// Query: *[    (_type == "landscape" && slug.current == $slug) ||    (_type == "page" && slug.current == $slug) ||    (_type == "kulturenPage" && $slug == "kulturen")  ][0]{ _type }
export type SLUG_TYPE_QUERY_RESULT =
  | {
      _type: "kulturenPage";
    }
  | {
      _type: "landscape";
    }
  | {
      _type: "page";
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    masthead,\n    nav,\n    cta,\n    footerMark,\n    footerBlurb,\n    footerQuote,\n    footerColumns,\n    footerBottomCopyright,\n    footerBottomTagline,\n    seo{\n      title,\n      description,\n      ogImage{ asset->{url, metadata{dimensions}}, alt }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    hero{\n      kicker,\n      title,\n      deck,\n      meta\n    },\n    signatureCard{\n      stamp,\n      foreLabel,\n      quote,\n      body,\n      scripture{ text, reference }\n    },\n    ticker{\n      items[]{ year, milestone }\n    },\n    vinyls{\n      kicker,\n      heading,\n      deck,\n      items[]{\n        cornerNumber,\n        cornerTag,\n        vinylAccent,\n        sleeveText,\n        vinylTopLabel,\n        vinylTitle,\n        vinylBottomLabel,\n        heading,\n        subhead,\n        body,\n        tracklist[]{ track, title, duration },\n        linkText,\n        linkHref\n      }\n    },\n    historicalThread{\n      kicker,\n      heading,\n      intro,\n      timeline[]{ year, place, heading, description }\n    },\n    hymn{\n      kicker,\n      quote,\n      attribution\n    },\n    contact{\n      kicker,\n      heading,\n      deck,\n      bookingLabel,\n      bookingHeading,\n      bookingBody,\n      bookingLinkText,\n      bookingLinkHref\n    },\n    seo{\n      title,\n      description,\n      ogImage{ asset->{url, metadata{dimensions}}, alt }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "kulturenPage"][0]{\n    hero{ eyebrow, title, subhead, deck },\n    chips{ label, count },\n    intro{ kicker, heading, signature, body },\n    outro{\n      kicker,\n      heading,\n      body,\n      actions[]{ text, href, style },\n      cardLead,\n      cardHeading\n    },\n    seo{\n      title,\n      description,\n      ogImage{ asset->{ url, metadata{ dimensions } }, alt }\n    },\n    "landscapes": *[_type == "landscape"] | order(order asc){\n      "slug": slug.current,\n      romanNumeral,\n      toponym,\n      period,\n      name,\n      motto,\n      shortName,\n      kulturenBgVariant,\n      kulturenArchiveCta,\n      kulturenCardTag,\n      kulturenEssay,\n      kulturenSidebar[]{\n        _type,\n        _key,\n        label,\n        emphasis,\n        value,\n        entries[]{ _key, year, text }\n      }\n    }\n  }\n': KULTUREN_QUERY_RESULT;
    '\n  *[_type == "landscape" && slug.current == $slug][0]{\n    name,\n    "slug": slug.current,\n    order,\n    romanNumeral,\n    toponym,\n    period,\n    accentColor,\n    eyebrow,\n    motto,\n    deck,\n    topicsLabel,\n    topics,\n    crumbBackText,\n    crumbBackHref,\n    emptyMeta,\n    emptyLabel,\n    emptyHeading,\n    emptyBody,\n    emptyActions[]{ text, href, style },\n    "entries": *[_type == "archiveEntry" && landscape._ref == ^._id] | order(publishedAt desc){\n      title,\n      "slug": slug.current,\n      publishedAt,\n      kind,\n      summary\n    },\n    seo{\n      title,\n      description,\n      ogImage{ asset->{url, metadata{dimensions}}, alt }\n    }\n  }\n': LANDSCAPE_QUERY_RESULT;
    '\n  *[_type == "landscape"] | order(order asc){\n    "slug": slug.current,\n    romanNumeral,\n    shortName,\n    order\n  }\n': LANDSCAPE_SIBLINGS_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    title,\n    accentColor,\n    blocks[]{\n      _type,\n      _key,\n      _type == "vinylHero" => {\n        eyebrow,\n        romanNumeral,\n        heading,\n        lede,\n        metaItems[]{ label, value },\n        vinylTop,\n        vinylTitle,\n        vinylBottom,\n        tickerItems\n      },\n      _type == "steppedList" => {\n        kicker,\n        heading,\n        deck,\n        items[]{\n          years,\n          label,\n          tag[]{ label, value },\n          body,\n          cuts[]{ cutLabel, cutTitle, cutDuration, cutHref }\n        }\n      },\n      _type == "cardGrid" => {\n        kicker,\n        heading,\n        deck,\n        cards[]{ roman, tag, cardHeading, cardBody }\n      },\n      _type == "pullQuote" => {\n        kicker,\n        quote,\n        attribution,\n        background,\n        borderTone\n      },\n      _type == "nextEssay" => {\n        kicker,\n        heading,\n        cards[]{ roman, tag, cardHeading, cta, href, colorScheme }\n      },\n      _type == "hymnHero" => {\n        eyebrow,\n        romanNumeral,\n        heading,\n        lede,\n        metaItems[]{ label, value },\n        glassCaptionTop,\n        glassQuote\n      },\n      _type == "scriptureStrip" => {\n        quote,\n        reference\n      },\n      _type == "stations" => {\n        kicker,\n        heading,\n        deck,\n        items[]{\n          roman,\n          years,\n          location,\n          heading,\n          where,\n          body,\n          quote{ text, attribution }\n        }\n      },\n      _type == "hymnal" => {\n        kicker,\n        heading,\n        deck,\n        columns[]{\n          header,\n          subhead,\n          rows[]{ number, title, sub, duration, href }\n        }\n      }\n    },\n    seo{\n      title,\n      description,\n      ogImage{ asset->{ url, metadata{ dimensions } }, alt }\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[\n    (_type == "landscape" && slug.current == $slug) ||\n    (_type == "page" && slug.current == $slug) ||\n    (_type == "kulturenPage" && $slug == "kulturen")\n  ][0]{ _type }\n': SLUG_TYPE_QUERY_RESULT;
  }
}
