/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TimelineEvent = {
  _type: "timelineEvent";
  year?: string;
  place?: string;
  heading?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type VinylTile = {
  _type: "vinylTile";
  cornerNumber?: string;
  cornerTag?: string;
  vinylAccent?: "barn" | "denim" | "brass";
  sleeveText?: string;
  vinylTopLabel?: string;
  vinylTitle?: string;
  vinylBottomLabel?: string;
  heading?: string;
  subhead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tracklist?: Array<
    {
      _key: string;
    } & VinylTrack
  >;
  linkText?: string;
  linkHref?: string;
};

export type VinylTrack = {
  _type: "vinylTrack";
  track?: string;
  title?: string;
  duration?: string;
};

export type TickerItem = {
  _type: "tickerItem";
  year?: string;
  milestone?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type FooterQuote = {
  _type: "footerQuote";
  text?: string;
  attribution?: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  title?: string;
  links?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type NavGroup = {
  _type: "navGroup";
  label?: string;
  href?: string;
  children?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: "navLink";
  mark?: string;
  label?: string;
  href?: string;
};

export type Masthead = {
  _type: "masthead";
  kicker?: string;
  name?: string;
  sub?: string;
  leftLine1?: string;
  leftLine2?: string;
  rightLine1?: string;
  rightLine2?: string;
};

export type LandscapeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "landscape";
};

export type ArchiveEntry = {
  _id: string;
  _type: "archiveEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  landscape?: LandscapeReference;
  publishedAt?: string;
  kind?: "anmeldelse" | "fund" | "fodnote" | "note";
  summary?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Landscape = {
  _id: string;
  _type: "landscape";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  shortName?: string;
  slug?: Slug;
  order?: number;
  romanNumeral?: string;
  toponym?: string;
  period?: string;
  accentColor?: "barn" | "denim" | "brass";
  eyebrow?: string;
  motto?: string;
  deck?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  topicsLabel?: string;
  topics?: Array<string>;
  crumbBackText?: string;
  crumbBackHref?: string;
  emptyMeta?: string;
  emptyLabel?: string;
  emptyHeading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  emptyBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  emptyActions?: Array<{
    text?: string;
    href?: string;
    style?: "primary" | "secondary";
    _key: string;
  }>;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    kicker?: string;
    title?: string;
    deck?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    meta?: Array<string>;
  };
  signatureCard?: {
    stamp?: string;
    foreLabel?: string;
    quote?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    scripture?: {
      text?: string;
      reference?: string;
    };
  };
  ticker?: {
    items?: Array<
      {
        _key: string;
      } & TickerItem
    >;
  };
  vinyls?: {
    kicker?: string;
    heading?: string;
    deck?: string;
    items?: Array<
      {
        _key: string;
      } & VinylTile
    >;
  };
  historicalThread?: {
    kicker?: string;
    heading?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    intro?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    timeline?: Array<
      {
        _key: string;
      } & TimelineEvent
    >;
  };
  hymn?: {
    kicker?: string;
    quote?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    attribution?: string;
  };
  contact?: {
    kicker?: string;
    heading?: string;
    deck?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    bookingLabel?: string;
    bookingHeading?: string;
    bookingBody?: string;
    bookingLinkText?: string;
    bookingLinkHref?: string;
  };
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  masthead?: Masthead;
  nav?: Array<
    {
      _key: string;
    } & NavGroup
  >;
  cta?: Cta;
  footerMark?: string;
  footerBlurb?: string;
  footerQuote?: FooterQuote;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  footerBottomCopyright?: string;
  footerBottomTagline?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TimelineEvent
  | VinylTile
  | VinylTrack
  | TickerItem
  | SanityImageAssetReference
  | Seo
  | FooterQuote
  | FooterColumn
  | Cta
  | NavGroup
  | NavLink
  | Masthead
  | LandscapeReference
  | ArchiveEntry
  | Slug
  | Landscape
  | HomePage
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/global.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    masthead,    nav,    cta,    footerMark,    footerBlurb,    footerQuote,    footerColumns,    footerBottomCopyright,    footerBottomTagline,    seo{      title,      description,      ogImage{ asset->{url, metadata{dimensions}}, alt }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  masthead: Masthead | null;
  nav: Array<
    {
      _key: string;
    } & NavGroup
  > | null;
  cta: Cta | null;
  footerMark: string | null;
  footerBlurb: string | null;
  footerQuote: FooterQuote | null;
  footerColumns: Array<
    {
      _key: string;
    } & FooterColumn
  > | null;
  footerBottomCopyright: string | null;
  footerBottomTagline: string | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/home.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    hero{      kicker,      title,      deck,      meta    },    signatureCard{      stamp,      foreLabel,      quote,      body,      scripture{ text, reference }    },    ticker{      items[]{ year, milestone }    },    vinyls{      kicker,      heading,      deck,      items[]{        cornerNumber,        cornerTag,        vinylAccent,        sleeveText,        vinylTopLabel,        vinylTitle,        vinylBottomLabel,        heading,        subhead,        body,        tracklist[]{ track, title, duration },        linkText,        linkHref      }    },    historicalThread{      kicker,      heading,      intro,      timeline[]{ year, place, heading, description }    },    hymn{      kicker,      quote,      attribution    },    contact{      kicker,      heading,      deck,      bookingLabel,      bookingHeading,      bookingBody,      bookingLinkText,      bookingLinkHref    },    seo{      title,      description,      ogImage{ asset->{url, metadata{dimensions}}, alt }    }  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    kicker: string | null;
    title: string | null;
    deck: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    meta: Array<string> | null;
  } | null;
  signatureCard: {
    stamp: string | null;
    foreLabel: string | null;
    quote: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    scripture: {
      text: string | null;
      reference: string | null;
    } | null;
  } | null;
  ticker: {
    items: Array<{
      year: string | null;
      milestone: string | null;
    }> | null;
  } | null;
  vinyls: {
    kicker: string | null;
    heading: string | null;
    deck: string | null;
    items: Array<{
      cornerNumber: string | null;
      cornerTag: string | null;
      vinylAccent: "barn" | "brass" | "denim" | null;
      sleeveText: string | null;
      vinylTopLabel: string | null;
      vinylTitle: string | null;
      vinylBottomLabel: string | null;
      heading: string | null;
      subhead: string | null;
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      tracklist: Array<{
        track: string | null;
        title: string | null;
        duration: string | null;
      }> | null;
      linkText: string | null;
      linkHref: string | null;
    }> | null;
  } | null;
  historicalThread: {
    kicker: string | null;
    heading: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    intro: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    timeline: Array<{
      year: string | null;
      place: string | null;
      heading: string | null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }> | null;
  } | null;
  hymn: {
    kicker: string | null;
    quote: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    attribution: string | null;
  } | null;
  contact: {
    kicker: string | null;
    heading: string | null;
    deck: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    bookingLabel: string | null;
    bookingHeading: string | null;
    bookingBody: string | null;
    bookingLinkText: string | null;
    bookingLinkHref: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/landscape.ts
// Variable: LANDSCAPE_QUERY
// Query: *[_type == "landscape" && slug.current == $slug][0]{    name,    "slug": slug.current,    order,    romanNumeral,    toponym,    period,    accentColor,    eyebrow,    motto,    deck,    topicsLabel,    topics,    crumbBackText,    crumbBackHref,    emptyMeta,    emptyLabel,    emptyHeading,    emptyBody,    emptyActions[]{ text, href, style },    "entries": *[_type == "archiveEntry" && landscape._ref == ^._id] | order(publishedAt desc){      title,      "slug": slug.current,      publishedAt,      kind,      summary    },    seo{      title,      description,      ogImage{ asset->{url, metadata{dimensions}}, alt }    }  }
export type LANDSCAPE_QUERY_RESULT = {
  name: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  order: number | null;
  romanNumeral: string | null;
  toponym: string | null;
  period: string | null;
  accentColor: "barn" | "brass" | "denim" | null;
  eyebrow: string | null;
  motto: string | null;
  deck: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  topicsLabel: string | null;
  topics: Array<string> | null;
  crumbBackText: string | null;
  crumbBackHref: string | null;
  emptyMeta: string | null;
  emptyLabel: string | null;
  emptyHeading: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  emptyBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  emptyActions: Array<{
    text: string | null;
    href: string | null;
    style: "primary" | "secondary" | null;
  }> | null;
  entries: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    kind: "anmeldelse" | "fodnote" | "fund" | "note" | null;
    summary: string | null;
  }>;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/landscape.ts
// Variable: LANDSCAPE_SIBLINGS_QUERY
// Query: *[_type == "landscape"] | order(order asc){    "slug": slug.current,    romanNumeral,    shortName,    order  }
export type LANDSCAPE_SIBLINGS_QUERY_RESULT = Array<{
  slug: string | null;
  romanNumeral: string | null;
  shortName: string | null;
  order: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    masthead,\n    nav,\n    cta,\n    footerMark,\n    footerBlurb,\n    footerQuote,\n    footerColumns,\n    footerBottomCopyright,\n    footerBottomTagline,\n    seo{\n      title,\n      description,\n      ogImage{ asset->{url, metadata{dimensions}}, alt }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    hero{\n      kicker,\n      title,\n      deck,\n      meta\n    },\n    signatureCard{\n      stamp,\n      foreLabel,\n      quote,\n      body,\n      scripture{ text, reference }\n    },\n    ticker{\n      items[]{ year, milestone }\n    },\n    vinyls{\n      kicker,\n      heading,\n      deck,\n      items[]{\n        cornerNumber,\n        cornerTag,\n        vinylAccent,\n        sleeveText,\n        vinylTopLabel,\n        vinylTitle,\n        vinylBottomLabel,\n        heading,\n        subhead,\n        body,\n        tracklist[]{ track, title, duration },\n        linkText,\n        linkHref\n      }\n    },\n    historicalThread{\n      kicker,\n      heading,\n      intro,\n      timeline[]{ year, place, heading, description }\n    },\n    hymn{\n      kicker,\n      quote,\n      attribution\n    },\n    contact{\n      kicker,\n      heading,\n      deck,\n      bookingLabel,\n      bookingHeading,\n      bookingBody,\n      bookingLinkText,\n      bookingLinkHref\n    },\n    seo{\n      title,\n      description,\n      ogImage{ asset->{url, metadata{dimensions}}, alt }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "landscape" && slug.current == $slug][0]{\n    name,\n    "slug": slug.current,\n    order,\n    romanNumeral,\n    toponym,\n    period,\n    accentColor,\n    eyebrow,\n    motto,\n    deck,\n    topicsLabel,\n    topics,\n    crumbBackText,\n    crumbBackHref,\n    emptyMeta,\n    emptyLabel,\n    emptyHeading,\n    emptyBody,\n    emptyActions[]{ text, href, style },\n    "entries": *[_type == "archiveEntry" && landscape._ref == ^._id] | order(publishedAt desc){\n      title,\n      "slug": slug.current,\n      publishedAt,\n      kind,\n      summary\n    },\n    seo{\n      title,\n      description,\n      ogImage{ asset->{url, metadata{dimensions}}, alt }\n    }\n  }\n': LANDSCAPE_QUERY_RESULT;
    '\n  *[_type == "landscape"] | order(order asc){\n    "slug": slug.current,\n    romanNumeral,\n    shortName,\n    order\n  }\n': LANDSCAPE_SIBLINGS_QUERY_RESULT;
  }
}
