/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FooterQuote = {
  _type: "footerQuote";
  text?: string;
  attribution?: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  title?: string;
  links?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type NavGroup = {
  _type: "navGroup";
  label?: string;
  href?: string;
  children?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: "navLink";
  mark?: string;
  label?: string;
  href?: string;
};

export type Masthead = {
  _type: "masthead";
  kicker?: string;
  name?: string;
  sub?: string;
  leftLine1?: string;
  leftLine2?: string;
  rightLine1?: string;
  rightLine2?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  masthead?: Masthead;
  nav?: Array<
    {
      _key: string;
    } & NavGroup
  >;
  cta?: Cta;
  footerMark?: string;
  footerBlurb?: string;
  footerQuote?: FooterQuote;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  footerBottomCopyright?: string;
  footerBottomTagline?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | FooterQuote
  | FooterColumn
  | Cta
  | NavGroup
  | NavLink
  | Masthead
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/queries/global.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    masthead,    nav,    cta,    footerMark,    footerBlurb,    footerQuote,    footerColumns,    footerBottomCopyright,    footerBottomTagline  }
export type SITE_SETTINGS_QUERY_RESULT = {
  masthead: Masthead | null;
  nav: Array<
    {
      _key: string;
    } & NavGroup
  > | null;
  cta: Cta | null;
  footerMark: string | null;
  footerBlurb: string | null;
  footerQuote: FooterQuote | null;
  footerColumns: Array<
    {
      _key: string;
    } & FooterColumn
  > | null;
  footerBottomCopyright: string | null;
  footerBottomTagline: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    masthead,\n    nav,\n    cta,\n    footerMark,\n    footerBlurb,\n    footerQuote,\n    footerColumns,\n    footerBottomCopyright,\n    footerBottomTagline\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
