import { defineArrayMember, defineField, defineType } from 'sanity'

export const vinylTile = defineType({
  name: 'vinylTile',
  title: 'Vinyl-felt',
  type: 'object',
  groups: [
    { name: 'card', title: 'Kort', default: true },
    { name: 'vinyl', title: 'Vinyl' },
    { name: 'content', title: 'Indhold' },
  ],
  fields: [
    defineField({
      name: 'cornerNumber',
      title: 'Hjørne — nummer',
      description: 'Fx "SIDE A · No. 01".',
      type: 'string',
      group: 'card',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'cornerTag',
      title: 'Hjørne — tag',
      description: 'Fx "33⅓ RPM".',
      type: 'string',
      group: 'card',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylAccent',
      title: 'Accentfarve',
      type: 'string',
      group: 'vinyl',
      options: {
        list: [
          { title: 'Barn (rød)', value: 'barn' },
          { title: 'Denim (blå)', value: 'denim' },
          { title: 'Brass (gul)', value: 'brass' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sleeveText',
      title: 'Sleeve-tekst',
      description: 'Lille tekst på pladeomslaget, fx "Side A · Long Play".',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylTopLabel',
      title: 'Plade — øverste linje',
      description: 'Fx "— Sun Records —".',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylTitle',
      title: 'Plade — titel',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylBottomLabel',
      title: 'Plade — nederste linje',
      description: 'Fx "Memphis · TN".',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heading',
      title: 'Overskrift',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'subhead',
      title: 'Undertitel',
      description: 'Fx "Boom-chicka-boom · 1955 — 2003".',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'body',
      title: 'Brødtekst',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'block', styles: [{ title: 'Normal', value: 'normal' }], lists: [] })],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tracklist',
      title: 'Sporliste',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'vinylTrack' })],
      validation: (Rule) => Rule.required().length(4),
    }),
    defineField({
      name: 'linkText',
      title: 'Link-tekst',
      description: 'Fx "Læs om musikeren".',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'linkHref',
      title: 'Link-sti',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: { heading: 'heading', subhead: 'subhead', accent: 'vinylAccent' },
    prepare: ({ heading, subhead, accent }) => ({
      title: heading,
      subtitle: `${accent ?? '—'} · ${subhead ?? ''}`,
    }),
  },
})
