import { defineArrayMember, defineField, defineType } from 'sanity'

export const vinylTile = defineType({
  name: 'vinylTile',
  title: 'Vinyl Tile',
  type: 'object',
  groups: [
    { name: 'card', title: 'Card', default: true },
    { name: 'vinyl', title: 'Vinyl' },
    { name: 'content', title: 'Content' },
  ],
  fields: [
    defineField({
      name: 'cornerNumber',
      title: 'Corner — number',
      description: 'E.g. “SIDE A · No. 01”.',
      type: 'string',
      group: 'card',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'cornerTag',
      title: 'Corner — tag',
      description: 'E.g. “33⅓ RPM”.',
      type: 'string',
      group: 'card',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylAccent',
      title: 'Accent colour',
      type: 'string',
      group: 'vinyl',
      options: {
        list: [
          { title: 'Barn (red)', value: 'barn' },
          { title: 'Denim (blue)', value: 'denim' },
          { title: 'Brass (yellow)', value: 'brass' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sleeveText',
      title: 'Sleeve text',
      description: 'Small text on the record sleeve, e.g. “Side A · Long Play”.',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylTopLabel',
      title: 'Record — top line',
      description: 'E.g. “— Sun Records —”.',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylTitle',
      title: 'Record — title',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vinylBottomLabel',
      title: 'Record — bottom line',
      description: 'E.g. “Memphis · TN”.',
      type: 'string',
      group: 'vinyl',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heading',
      title: 'Heading',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'subhead',
      title: 'Subhead',
      description: 'E.g. “Boom-chicka-boom · 1955 — 2003”.',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'body',
      title: 'Body text',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'block', styles: [{ title: 'Normal', value: 'normal' }], lists: [] })],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tracklist',
      title: 'Songs',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'vinylTrack' })],
      validation: (Rule) => Rule.required().length(4),
    }),
    defineField({
      name: 'linkText',
      title: 'Link text',
      description: 'E.g. “Læs om musikeren”.',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'linkHref',
      title: 'Link path',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: { heading: 'heading', subhead: 'subhead', accent: 'vinylAccent' },
    prepare: ({ heading, subhead, accent }) => ({
      title: heading,
      subtitle: `${accent ?? '—'} · ${subhead ?? ''}`,
    }),
  },
})
