import { HomeIcon } from '@sanity/icons'
import { defineArrayMember, defineField, defineType } from 'sanity'

const inlineBlock = defineArrayMember({
  type: 'block',
  styles: [{ title: 'Normal', value: 'normal' }],
  lists: [],
})

export const homePage = defineType({
  name: 'homePage',
  title: 'Forside — Johnny og jeg',
  type: 'document',
  icon: HomeIcon,
  groups: [
    { name: 'hero', title: 'Hero', default: true },
    { name: 'signatureCard', title: 'Signaturkort' },
    { name: 'ticker', title: 'Ticker' },
    { name: 'vinyls', title: 'Vinyl-felter' },
    { name: 'historicalThread', title: 'Historisk tråd' },
    { name: 'hymn', title: 'Salme' },
    { name: 'contact', title: 'Kontakt' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'object',
      group: 'hero',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'kicker',
          title: 'Kicker',
          description: 'Valgfri linje over titlen. Designet på forsiden viser ingen kicker — lad være tom.',
          type: 'string',
        }),
        defineField({
          name: 'title',
          title: 'Titel',
          description: 'Skriv "Johnny og jeg" — "og" gengives med en rød ampersand.',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'deck',
          title: 'Deck',
          description: 'Italic intro-afsnit. Første bogstav får drop-cap.',
          type: 'array',
          of: [inlineBlock],
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'meta',
          title: 'Meta-linjer',
          description: 'Op til 3 metadata-strenge, fx "Et essay af Mads", "Læsetid ~12 min."',
          type: 'array',
          of: [defineArrayMember({ type: 'string' })],
          validation: (Rule) => Rule.max(3),
        }),
      ],
    }),
    defineField({
      name: 'signatureCard',
      title: 'Signaturkort',
      type: 'object',
      group: 'signatureCard',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'stamp',
          title: 'Stempel',
          description: 'Cirkulært stempel-tekst, fx "Sign. JR Cash 1955—2003".',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'foreLabel',
          title: 'Fore-label',
          description: 'Lille label over titlen, fx "— Forord —".',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'quote',
          title: 'Titel-citat',
          description: 'Fx "Hello. I’m Johnny Cash."',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'body',
          title: 'Brødtekst',
          type: 'array',
          of: [inlineBlock],
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'scripture',
          title: 'Skriftsted',
          description: 'Citat fra Bibelen + reference.',
          type: 'object',
          fields: [
            defineField({
              name: 'text',
              title: 'Tekst',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'reference',
              title: 'Reference',
              description: 'Fx "Rom. 1:16".',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'ticker',
      title: 'Ticker',
      type: 'object',
      group: 'ticker',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'items',
          title: 'Elementer',
          type: 'array',
          of: [defineArrayMember({ type: 'tickerItem' })],
          validation: (Rule) => Rule.required().min(4),
        }),
      ],
    }),
    defineField({
      name: 'vinyls',
      title: 'Vinyl-felter',
      type: 'object',
      group: 'vinyls',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'kicker',
          title: 'Kicker',
          description: 'Fx "— Tre rubrikker · Side A · Side B · Side C —".',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'heading',
          title: 'Overskrift',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'deck',
          title: 'Deck',
          type: 'text',
          rows: 3,
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'items',
          title: 'Felter',
          description: 'Tre felter — én for hver "side" af projektet.',
          type: 'array',
          of: [defineArrayMember({ type: 'vinylTile' })],
          validation: (Rule) => Rule.required().length(3),
        }),
      ],
    }),
    defineField({
      name: 'historicalThread',
      title: 'Historisk tråd',
      type: 'object',
      group: 'historicalThread',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'kicker',
          title: 'Kicker',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'heading',
          title: 'Overskrift',
          description: 'Brug *kursiv* for at fremhæve ord i rød.',
          type: 'array',
          of: [inlineBlock],
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'intro',
          title: 'Intro',
          type: 'array',
          of: [inlineBlock],
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'timeline',
          title: 'Tidslinje',
          description: 'Otte begivenheder — gengivet som to rækker à fire.',
          type: 'array',
          of: [defineArrayMember({ type: 'timelineEvent' })],
          validation: (Rule) => Rule.required().length(8),
        }),
      ],
    }),
    defineField({
      name: 'hymn',
      title: 'Salme',
      type: 'object',
      group: 'hymn',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'kicker',
          title: 'Kicker',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'quote',
          title: 'Citat',
          type: 'array',
          of: [inlineBlock],
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'attribution',
          title: 'Attribuering',
          description: 'Fx "Mads ✶ Forord til “Johnny og jeg” ✶ 2026".',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    defineField({
      name: 'contact',
      title: 'Kontakt',
      type: 'object',
      group: 'contact',
      validation: (Rule) => Rule.required(),
      fields: [
        defineField({
          name: 'kicker',
          title: 'Kicker',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'heading',
          title: 'Overskrift',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'deck',
          title: 'Deck',
          type: 'array',
          of: [inlineBlock],
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bookingLabel',
          title: 'Foredrag — label',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bookingHeading',
          title: 'Foredrag — overskrift',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bookingBody',
          title: 'Foredrag — tekst',
          type: 'text',
          rows: 3,
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bookingLinkText',
          title: 'Foredrag — knaptekst',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bookingLinkHref',
          title: 'Foredrag — knapsti',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Forside — Johnny og jeg' }),
  },
})
